name: "EC2 auto deploy"

on:
  push:
    branches: ["master"]

jobs:
  analyze:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: BuildDeploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          cd ${{ secrets.SERVER_PULL_DIR }}
          git fetch origin master
          git reset --hard origin/master
          ${{ secrets.JP_BUILD }}
          ${{ secrets.JP_DEPLOY }}
